//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1378.
// 
#pragma warning disable 1591

namespace CheckersClient.cws {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CheckersWSSEIBinding", Namespace="urn:CheckersWS/wsdl")]
    public partial class CheckersWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback firstPlayerOperationCompleted;
        
        private System.Threading.SendOrPostCallback gameEndOperationCompleted;
        
        private System.Threading.SendOrPostCallback gameStartedOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOpornentIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback movePieceOperationCompleted;
        
        private System.Threading.SendOrPostCallback nextMoveOperationCompleted;
        
        private System.Threading.SendOrPostCallback registerPlayerOperationCompleted;
        
        private System.Threading.SendOrPostCallback restartGameOperationCompleted;
        
        private System.Threading.SendOrPostCallback startGameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CheckersWS() {
            this.Url = global::CheckersClient.Properties.Settings.Default.CheckersClient_cws_CheckersWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event firstPlayerCompletedEventHandler firstPlayerCompleted;
        
        /// <remarks/>
        public event gameEndCompletedEventHandler gameEndCompleted;
        
        /// <remarks/>
        public event gameStartedCompletedEventHandler gameStartedCompleted;
        
        /// <remarks/>
        public event getOpornentIDCompletedEventHandler getOpornentIDCompleted;
        
        /// <remarks/>
        public event getSatusCompletedEventHandler getSatusCompleted;
        
        /// <remarks/>
        public event movePieceCompletedEventHandler movePieceCompleted;
        
        /// <remarks/>
        public event nextMoveCompletedEventHandler nextMoveCompleted;
        
        /// <remarks/>
        public event registerPlayerCompletedEventHandler registerPlayerCompleted;
        
        /// <remarks/>
        public event restartGameCompletedEventHandler restartGameCompleted;
        
        /// <remarks/>
        public event startGameCompletedEventHandler startGameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("firstPlayerResponse", Namespace="urn:CheckersWS/types")]
        public firstPlayerResponse firstPlayer([System.Xml.Serialization.XmlElementAttribute("firstPlayer", Namespace="urn:CheckersWS/types")] firstPlayer firstPlayer1) {
            object[] results = this.Invoke("firstPlayer", new object[] {
                        firstPlayer1});
            return ((firstPlayerResponse)(results[0]));
        }
        
        /// <remarks/>
        public void firstPlayerAsync(firstPlayer firstPlayer1) {
            this.firstPlayerAsync(firstPlayer1, null);
        }
        
        /// <remarks/>
        public void firstPlayerAsync(firstPlayer firstPlayer1, object userState) {
            if ((this.firstPlayerOperationCompleted == null)) {
                this.firstPlayerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfirstPlayerOperationCompleted);
            }
            this.InvokeAsync("firstPlayer", new object[] {
                        firstPlayer1}, this.firstPlayerOperationCompleted, userState);
        }
        
        private void OnfirstPlayerOperationCompleted(object arg) {
            if ((this.firstPlayerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.firstPlayerCompleted(this, new firstPlayerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("gameEndResponse", Namespace="urn:CheckersWS/types")]
        public gameEndResponse gameEnd([System.Xml.Serialization.XmlElementAttribute("gameEnd", Namespace="urn:CheckersWS/types")] gameEnd gameEnd1) {
            object[] results = this.Invoke("gameEnd", new object[] {
                        gameEnd1});
            return ((gameEndResponse)(results[0]));
        }
        
        /// <remarks/>
        public void gameEndAsync(gameEnd gameEnd1) {
            this.gameEndAsync(gameEnd1, null);
        }
        
        /// <remarks/>
        public void gameEndAsync(gameEnd gameEnd1, object userState) {
            if ((this.gameEndOperationCompleted == null)) {
                this.gameEndOperationCompleted = new System.Threading.SendOrPostCallback(this.OngameEndOperationCompleted);
            }
            this.InvokeAsync("gameEnd", new object[] {
                        gameEnd1}, this.gameEndOperationCompleted, userState);
        }
        
        private void OngameEndOperationCompleted(object arg) {
            if ((this.gameEndCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.gameEndCompleted(this, new gameEndCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("gameStartedResponse", Namespace="urn:CheckersWS/types")]
        public gameStartedResponse gameStarted([System.Xml.Serialization.XmlElementAttribute("gameStarted", Namespace="urn:CheckersWS/types")] gameStarted gameStarted1) {
            object[] results = this.Invoke("gameStarted", new object[] {
                        gameStarted1});
            return ((gameStartedResponse)(results[0]));
        }
        
        /// <remarks/>
        public void gameStartedAsync(gameStarted gameStarted1) {
            this.gameStartedAsync(gameStarted1, null);
        }
        
        /// <remarks/>
        public void gameStartedAsync(gameStarted gameStarted1, object userState) {
            if ((this.gameStartedOperationCompleted == null)) {
                this.gameStartedOperationCompleted = new System.Threading.SendOrPostCallback(this.OngameStartedOperationCompleted);
            }
            this.InvokeAsync("gameStarted", new object[] {
                        gameStarted1}, this.gameStartedOperationCompleted, userState);
        }
        
        private void OngameStartedOperationCompleted(object arg) {
            if ((this.gameStartedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.gameStartedCompleted(this, new gameStartedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getOpornentIDResponse", Namespace="urn:CheckersWS/types")]
        public getOpornentIDResponse getOpornentID([System.Xml.Serialization.XmlElementAttribute("getOpornentID", Namespace="urn:CheckersWS/types")] getOpornentID getOpornentID1) {
            object[] results = this.Invoke("getOpornentID", new object[] {
                        getOpornentID1});
            return ((getOpornentIDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getOpornentIDAsync(getOpornentID getOpornentID1) {
            this.getOpornentIDAsync(getOpornentID1, null);
        }
        
        /// <remarks/>
        public void getOpornentIDAsync(getOpornentID getOpornentID1, object userState) {
            if ((this.getOpornentIDOperationCompleted == null)) {
                this.getOpornentIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOpornentIDOperationCompleted);
            }
            this.InvokeAsync("getOpornentID", new object[] {
                        getOpornentID1}, this.getOpornentIDOperationCompleted, userState);
        }
        
        private void OngetOpornentIDOperationCompleted(object arg) {
            if ((this.getOpornentIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOpornentIDCompleted(this, new getOpornentIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getSatusResponse", Namespace="urn:CheckersWS/types")]
        public getSatusResponse getSatus([System.Xml.Serialization.XmlElementAttribute("getSatus", Namespace="urn:CheckersWS/types")] getSatus getSatus1) {
            object[] results = this.Invoke("getSatus", new object[] {
                        getSatus1});
            return ((getSatusResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getSatusAsync(getSatus getSatus1) {
            this.getSatusAsync(getSatus1, null);
        }
        
        /// <remarks/>
        public void getSatusAsync(getSatus getSatus1, object userState) {
            if ((this.getSatusOperationCompleted == null)) {
                this.getSatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSatusOperationCompleted);
            }
            this.InvokeAsync("getSatus", new object[] {
                        getSatus1}, this.getSatusOperationCompleted, userState);
        }
        
        private void OngetSatusOperationCompleted(object arg) {
            if ((this.getSatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSatusCompleted(this, new getSatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("movePieceResponse", Namespace="urn:CheckersWS/types")]
        public movePieceResponse movePiece([System.Xml.Serialization.XmlElementAttribute("movePiece", Namespace="urn:CheckersWS/types")] movePiece movePiece1) {
            object[] results = this.Invoke("movePiece", new object[] {
                        movePiece1});
            return ((movePieceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void movePieceAsync(movePiece movePiece1) {
            this.movePieceAsync(movePiece1, null);
        }
        
        /// <remarks/>
        public void movePieceAsync(movePiece movePiece1, object userState) {
            if ((this.movePieceOperationCompleted == null)) {
                this.movePieceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmovePieceOperationCompleted);
            }
            this.InvokeAsync("movePiece", new object[] {
                        movePiece1}, this.movePieceOperationCompleted, userState);
        }
        
        private void OnmovePieceOperationCompleted(object arg) {
            if ((this.movePieceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.movePieceCompleted(this, new movePieceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("nextMoveResponse", Namespace="urn:CheckersWS/types")]
        public nextMoveResponse nextMove([System.Xml.Serialization.XmlElementAttribute("nextMove", Namespace="urn:CheckersWS/types")] nextMove nextMove1) {
            object[] results = this.Invoke("nextMove", new object[] {
                        nextMove1});
            return ((nextMoveResponse)(results[0]));
        }
        
        /// <remarks/>
        public void nextMoveAsync(nextMove nextMove1) {
            this.nextMoveAsync(nextMove1, null);
        }
        
        /// <remarks/>
        public void nextMoveAsync(nextMove nextMove1, object userState) {
            if ((this.nextMoveOperationCompleted == null)) {
                this.nextMoveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnextMoveOperationCompleted);
            }
            this.InvokeAsync("nextMove", new object[] {
                        nextMove1}, this.nextMoveOperationCompleted, userState);
        }
        
        private void OnnextMoveOperationCompleted(object arg) {
            if ((this.nextMoveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nextMoveCompleted(this, new nextMoveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("registerPlayerResponse", Namespace="urn:CheckersWS/types")]
        public registerPlayerResponse registerPlayer([System.Xml.Serialization.XmlElementAttribute("registerPlayer", Namespace="urn:CheckersWS/types")] registerPlayer registerPlayer1) {
            object[] results = this.Invoke("registerPlayer", new object[] {
                        registerPlayer1});
            return ((registerPlayerResponse)(results[0]));
        }
        
        /// <remarks/>
        public void registerPlayerAsync(registerPlayer registerPlayer1) {
            this.registerPlayerAsync(registerPlayer1, null);
        }
        
        /// <remarks/>
        public void registerPlayerAsync(registerPlayer registerPlayer1, object userState) {
            if ((this.registerPlayerOperationCompleted == null)) {
                this.registerPlayerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregisterPlayerOperationCompleted);
            }
            this.InvokeAsync("registerPlayer", new object[] {
                        registerPlayer1}, this.registerPlayerOperationCompleted, userState);
        }
        
        private void OnregisterPlayerOperationCompleted(object arg) {
            if ((this.registerPlayerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registerPlayerCompleted(this, new registerPlayerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("restartGameResponse", Namespace="urn:CheckersWS/types")]
        public restartGameResponse restartGame([System.Xml.Serialization.XmlElementAttribute("restartGame", Namespace="urn:CheckersWS/types")] restartGame restartGame1) {
            object[] results = this.Invoke("restartGame", new object[] {
                        restartGame1});
            return ((restartGameResponse)(results[0]));
        }
        
        /// <remarks/>
        public void restartGameAsync(restartGame restartGame1) {
            this.restartGameAsync(restartGame1, null);
        }
        
        /// <remarks/>
        public void restartGameAsync(restartGame restartGame1, object userState) {
            if ((this.restartGameOperationCompleted == null)) {
                this.restartGameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrestartGameOperationCompleted);
            }
            this.InvokeAsync("restartGame", new object[] {
                        restartGame1}, this.restartGameOperationCompleted, userState);
        }
        
        private void OnrestartGameOperationCompleted(object arg) {
            if ((this.restartGameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.restartGameCompleted(this, new restartGameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("startGameResponse", Namespace="urn:CheckersWS/types")]
        public startGameResponse startGame([System.Xml.Serialization.XmlElementAttribute("startGame", Namespace="urn:CheckersWS/types")] startGame startGame1) {
            object[] results = this.Invoke("startGame", new object[] {
                        startGame1});
            return ((startGameResponse)(results[0]));
        }
        
        /// <remarks/>
        public void startGameAsync(startGame startGame1) {
            this.startGameAsync(startGame1, null);
        }
        
        /// <remarks/>
        public void startGameAsync(startGame startGame1, object userState) {
            if ((this.startGameOperationCompleted == null)) {
                this.startGameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstartGameOperationCompleted);
            }
            this.InvokeAsync("startGame", new object[] {
                        startGame1}, this.startGameOperationCompleted, userState);
        }
        
        private void OnstartGameOperationCompleted(object arg) {
            if ((this.startGameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.startGameCompleted(this, new startGameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class firstPlayer {
        
        private int int_1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int int_1 {
            get {
                return this.int_1Field;
            }
            set {
                this.int_1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class startGameResponse {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class startGame {
        
        private int int_1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int int_1 {
            get {
                return this.int_1Field;
            }
            set {
                this.int_1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class restartGameResponse {
        
        private int resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class restartGame {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class registerPlayerResponse {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class registerPlayer {
        
        private int int_1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int int_1 {
            get {
                return this.int_1Field;
            }
            set {
                this.int_1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class nextMoveResponse {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class nextMove {
        
        private int int_1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int int_1 {
            get {
                return this.int_1Field;
            }
            set {
                this.int_1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class movePieceResponse {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class movePiece {
        
        private int int_1Field;
        
        private int int_2Field;
        
        private int int_3Field;
        
        private int int_4Field;
        
        private int int_5Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int int_1 {
            get {
                return this.int_1Field;
            }
            set {
                this.int_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int int_2 {
            get {
                return this.int_2Field;
            }
            set {
                this.int_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int int_3 {
            get {
                return this.int_3Field;
            }
            set {
                this.int_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int int_4 {
            get {
                return this.int_4Field;
            }
            set {
                this.int_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int int_5 {
            get {
                return this.int_5Field;
            }
            set {
                this.int_5Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class getSatusResponse {
        
        private int resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class getSatus {
        
        private int int_1Field;
        
        private int int_2Field;
        
        private int int_3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int int_1 {
            get {
                return this.int_1Field;
            }
            set {
                this.int_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int int_2 {
            get {
                return this.int_2Field;
            }
            set {
                this.int_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int int_3 {
            get {
                return this.int_3Field;
            }
            set {
                this.int_3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class getOpornentIDResponse {
        
        private int resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class getOpornentID {
        
        private int int_1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int int_1 {
            get {
                return this.int_1Field;
            }
            set {
                this.int_1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class gameStartedResponse {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class gameStarted {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class gameEndResponse {
        
        private int resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class gameEnd {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1378")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CheckersWS/types")]
    public partial class firstPlayerResponse {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void firstPlayerCompletedEventHandler(object sender, firstPlayerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class firstPlayerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal firstPlayerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public firstPlayerResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((firstPlayerResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void gameEndCompletedEventHandler(object sender, gameEndCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class gameEndCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal gameEndCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public gameEndResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((gameEndResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void gameStartedCompletedEventHandler(object sender, gameStartedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class gameStartedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal gameStartedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public gameStartedResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((gameStartedResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void getOpornentIDCompletedEventHandler(object sender, getOpornentIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOpornentIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOpornentIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getOpornentIDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getOpornentIDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void getSatusCompletedEventHandler(object sender, getSatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getSatusResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getSatusResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void movePieceCompletedEventHandler(object sender, movePieceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class movePieceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal movePieceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public movePieceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((movePieceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void nextMoveCompletedEventHandler(object sender, nextMoveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nextMoveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nextMoveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public nextMoveResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((nextMoveResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void registerPlayerCompletedEventHandler(object sender, registerPlayerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registerPlayerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registerPlayerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public registerPlayerResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((registerPlayerResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void restartGameCompletedEventHandler(object sender, restartGameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class restartGameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal restartGameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public restartGameResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((restartGameResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void startGameCompletedEventHandler(object sender, startGameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class startGameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal startGameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public startGameResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((startGameResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591